### ISSUE TITLE
Doesn't parse AirTunes AppleLossless a=rtpmap lines

### ISSUE THREAD

**Issue by DuBistKomisch** [clux/sdp-transform#30]
An example is available [here](https://nto.github.io/AirPlay.html#audio-rtsprequests) (the first example under `ANNOUNCE`).

Specifically this line:
`a=rtpmap:96 AppleLossless`
goes into `media[i].invalid` as-is. Tested in version 1.4.0 and 1.4.1.

Does the SDP spec require it to be followed by `/<rate>`? Even if so, it'd be nice to have this parsed and set `media[i].rtp[j].rate` to undefined if it's not present.

**Comment by clux** [comment]
RFC4566 implies it's not an optional parameter.

That said, an additional fallback rule can be added to the grammar to deal with it. I am a little busy for a while now though. PRs welcome :]

**Comment by DuBistKomisch** [comment]
Thanks for the quick reply!
Cool, I'll try to submit a PR tomorrow :)

**Comment by clux** [comment]
Leaving this open so that I remember to add the compose test before publishing.

**Comment by clux** [comment]
Published in sdp-transform@1.5.0

Thanks a  lot!
