### ISSUE TITLE
Parse fmtp configuration

### ISSUE THREAD

**Issue by beradrian** [clux/sdp-transform#32]
Instead of config, I think it will be useful to have parameters in fmtp.

**Comment by clux** [comment]
It's hard to create inverses for it without having tons of rules though.
You can always use [parseFmtpConfig](https://github.com/clux/sdp-transform#parser-postprocessing)

**Comment by beradrian** [comment]
There is also writeFmtpConfig and writePayloads?

**Comment by clux** [comment]
No. The parse helper was only really thrown in at the end, and tbh, it feels a bit out of place. t's hard to make a good writer that takes into account all the different things you can have in a config without duplicating the information. This module is not really here to make sense of the SDP, it's just for serialization + deserialization. What you want is probably best served by adding a layer on top of sdp-transform.

**Comment by beradrian** [comment]
I still think that this will be the best place, at least for something like writeFmtpParams.

**Comment by clux** [comment]
Except the string such a function would return have to be placed back onto the object correctly to be useful. If you are using such a function you should have it contained in some other place that interfaces with sdp-transform.

New helpers like this are not going to make it in here. In fact, the ones that are currently here are likely to be removed in the next major version as well.

**Comment by beradrian** [comment]
What about this - passing an options object to the parse function with the following fields

    {
        parseFmtpConfig: true,
        parsePayloads: true,
        aggregatePayloads: true
    }

and then the config will be an object with the corresponding properties instead of a string, payloads will be an array instead of a string. As for `aggregatePayloads`, this will mean that the `payloads` array will contain objects instead of numbers with the following properties: `rtp`, `fmtp` and `id` (or `payloadId`).
