### ISSUE TITLE
tcptype is not being set on write()

### ISSUE THREAD

**Issue by virtuacoplenny** [clux/sdp-transform#35]
After doing a .parse() on a sdp with a candidate that specifies tcptype, doing a write() will cause the tcptype to be blank.

Before:
`a=candidate:229815620 1 tcp 1518280447 0.0.0.0 0 typ host tcptype active generation 0`

After:
`a=candidate:229815620 1 tcp 1518280447 0.0.0.0 0 typ host tcptype  generation 0`

**Comment by clux** [comment]
Yeah, that was not considered. Had not encountered anyone doing TCP ICE. Thanks for doing this, and adding tests.

Published in sdp-transform@1.5.2
