### ISSUE TITLE
ssrc must admit no value

### ISSUE THREAD

**Issue by ibc** [clux/sdp-transform#40]
``` js
let objSsrc = {
    id: 12345678,
    attribute: 'foo'
};

obj.media[0].ssrcs.push(objSsrc);
```

This produces: `a=ssrc:12345678 foo:undefined`, which is wrong given that attribute value is not mandatory.

RFC 5576 refers to RFC 4566 when it comes to define the `attribute` syntax (which is generic):
- https://tools.ietf.org/html/rfc5576#section-10:

```
   ssrc-attr = "ssrc:" ssrc-id SP attribute
   ; The base definition of "attribute" is in RFC 4566.
   ; (It is the content of "a=" lines.)
```

**Comment by ibc** [comment]
More:

```
  https://tools.ietf.org/html/rfc5576#section-4.1

4.1.  The "ssrc" Media Attribute

   a=ssrc:<ssrc-id> <attribute>
   a=ssrc:<ssrc-id> <attribute>:<value>
```

**Comment by clux** [comment]
Hm, yes. That's wrong. [a=ssrc](https://github.com/clux/sdp-transform/blob/dc70c6f6f55c548ea1428a5c44d3b569d3de69a9/lib/grammar.js#L207-L212) needs a better regex and format function. I'm a bit busy this week, feel free to submit a PR.

**Comment by ibc** [comment]
Will take a look.

**Comment by zxcpoiu** [comment]
@ibc 

I made a PR #50 which fix this issue.
you may want to have a look and see if it's correct.

**Comment by ibc** [comment]
```js
reg: /^ssrc:(\d*) ([\w_]*)(?::(.*))?/
```

Is that `?::` correct? (I mean the double `::`)

**Comment by zxcpoiu** [comment]
I'm not sure, just learn this cool regexp from this repo, but it works :smile: 

seems `(?:XXXXX)?` is a regexp indicates a matching group XXXXX may appear or not.
and in this case, XXXXX = `:(.*)` --- a separator `:`  with the value part

**Comment by ibc** [comment]
Ok, it seems that such a `?:` makes the matching group not to appear in the matching result (which makes sense because we don't want the `:` but just the value after it).

**Comment by clux** [comment]
guess one of those colons could be escaped `\:` for readability
