### ISSUE TITLE
parseFmtpConfig doesn't support base64 encoded strings

### ISSUE THREAD

**Issue by lmoj** [clux/sdp-transform#42]
H264 media items almost always have a base64-encoded sprop-parameter-sets property:
```
fmtp:96 packetization-mode=1;profile-level-id=42001F;sprop-parameter-sets=Z0IAH5WoFAFuQA==,aM48gA==
```
and the parser fails because of the multiple equal signs.

**Comment by clux** [comment]
Landed in sdp-transform@1.6.1. Thanks again.
