### ISSUE TITLE
Valid encoding names

### ISSUE THREAD

**Issue by oskbor** [clux/sdp-transform#44]
Hi there!
We have this line in our sdp data:
`a=rtpmap:99 image.svg.data/90000`
This lib uses a regex that only parses `image` as the encoding name (and fails to parse the clock rate).
Do you have any specification regarding if `image.svg.data` is a valid encoding name, or if the regex should be updated to allow dots in the encoding name?

**Comment by clux** [comment]
Hello!

That *should* be valid, I think. The [rfc](https://tools.ietf.org/html/rfc4566), basically only says to treat slashes or spaces special for this `a=` line, so it should be safe to extend the regex.

**Comment by clux** [comment]
Implemented in sdp-transform 1.6.2 thanks to @alexanderklintstrom :)
