### ISSUE TITLE
How to set global a=msid-semantic attribute?

### ISSUE THREAD

**Issue by ibc** [clux/sdp-transform#46]
I want to set `a=msid-semantic: WMS 5kAAIomHNlen3snVvaSMUzojvdRtLpKBO8o3` into the global section of the SDP.

Doing this does not work:

```js
var sdp = {};
// [...]

sdp['msid-semantic'] = 'WMS 5kAAIomHNlen3snVvaSMUzojvdRtLpKBO8o3';

sdpTransform.write(sdp);
```

The generated SDP string does not contain global 'msid-semantic' attribute.

Is there a way to add custom (or non natively supported by this library) global attributes into a SDP?

**Comment by clux** [comment]
`msid-semantic` parses into an object with keys `['semantic', 'token']` if you look at the grammar. So you need to give it an object with those values at least.

**Comment by ibc** [comment]
Opps, I searched the sources for `msid-semantic` rather than `msidSemantic` :)

Thanks. However a proper documentation with the supported attributes (and their syntax) would be nice.
