### ISSUE TITLE
a=rtcp-mux-only

### ISSUE THREAD

**Issue by ibc** [clux/sdp-transform#48]
There is a [draft](https://tools.ietf.org/html/draft-ietf-mmusic-mux-exclusive) defining a new SDP media attribute: `a=rtcp-mux-only`.

I don't request that this library implements all the SDP attributes defined in ongoing drafts but, is there any way to append such an attribute or any unknown/custom one?:

```js
objMedia.rtcpMux = 'rtcp-mux';
objMedia.rtcpMuxOnly = 'rtcp-mux-only';  // This is ignored
```

**Comment by clux** [comment]
Yeah it's easy to add these things. All that's needed on this side is this appended to the a-line grammar:

```js
// grammar.js
    { //a=rtcp-mux
      name: 'rtcpmux',
      reg: /^(rtcp-mux)/
    },
```

provided it's a single value type line only (which from quickly searching the rfc it looks like it is).

Then you could parse an sdp with such a line and you would have `sdp.media[x].rtcpmux` or `sdp.session.rtcpmux` (depending on where the a= line was) set to `rtcp-mux`.

If it's reasonable stable line, I'm happy to add it.

**Comment by ibc** [comment]
Thanks. Let's close this for now. I'll come back if the draft advances so it makes sense to include its new attribute.
