### ISSUE TITLE
Wrong RTP header extension parsing when it includes a direction

### ISSUE THREAD

**Issue by ibc** [clux/sdp-transform#51]
The following valid RTP header extension attribute:

```
a=extmap:1/sendonly urn:ietf:params:rtp-hdrext:ssrc-audio-level
```

produces the following parsed object:

```js
{
  uri:   "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
  value: "1/sendonly"
}
```

It's wrong. `value` should be `1` (numeric) and a new `direction` key should be `sendonly`.

BNF spec: https://tools.ietf.org/html/rfc5285#section-7

**Comment by clux** [comment]
Yeah, the current method is a bit lazy:

https://github.com/clux/sdp-transform/blob/8794bce963759ca3301fc9430b9869d3014fbc89/lib/grammar.js#L99-L109

A better method here that accepts another optional field is welcome. Don't have too much time to look at it myself at the moment, but will merge a reasonable change with tests.

**Comment by ibc** [comment]
Pull Request #52 fixes (and improves) this.

**Comment by clux** [comment]
I will publish a new version with it later today. Not sure if it should be a major bump, I think it could technically break some parsing a little bit.

**Comment by ibc** [comment]
Humm, may be. IMHO the previous behavior was a bit "buggy" (in the sense that, even when there was no `direction`, `value` was an integer). So in my app, I am doing this "hack":

```js
let extId = parseInt(ext.value);
```

But, anyhow, the API changes since `value` is no longer a string nor it includes the `direction` so a major bump makes sense. Well, numbers are free! :)

**Comment by clux** [comment]
Yeah, ended up bumping the major just to be sure. Hate it when patch bumps break my code underneath me :)

sdp-transform@2.0.0 out now.

Thanks again.

**Comment by ibc** [comment]
Great, thanks!
