### ISSUE TITLE
Need a way to write custom attributes

### ISSUE THREAD

**Issue by ibc** [clux/sdp-transform#57]
Coming to my mind:

* `a=x-google-flag:conference`: custom Chrome stuff required to use VP8 simulcast.
* `a=rid`: https://tools.ietf.org/html/draft-ietf-mmusic-rid
* `a=simulcast`: https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast

I understand that adding the ability to write custom attributes while not being able to read/parse them makes no much sense. However, which is the way to move on with missing fields? Is it sending a PR for each new field the way to go?

**Comment by clux** [comment]
Hm, maybe there's a nice way of allowing custom ones for drafty stuff. I'll think about it a bit. For now, I guess PRs are fine.

It doesn't hurt to have draft attributes in the grammar even if they are not fully locked down, they can always be updated later, and it's better than having them in the `invalids` array if they are actually useful to parse.

**Comment by ibc** [comment]
OK, for now I'll send PRs for new fields. :)

**Comment by ibc** [comment]
Let me a question please. I'm trying to add the `a=rid` attribute:

```js
    { //a=rid:1 send max-width=1280;max-height=720;max-fps=30;depend=0
      push: 'rids',
      reg: /^rid:([\d\w]+) (\w+)(?: ([\S| ]*))/,
      names: ['id', 'direction', 'config'],
      format: function (o) {
        return (o.config) ? "rid:%s %s %s" : "rid:%s %s";
      }
    }
```

However, I don't know how to make `o.media[idx].rids` be an array. In fact, by looking at the code, I don't understand why `o.media[idx].ssrcs` is an array. Where is that defined?

I mean, if an SDP "m" section has a single `a=ssrc` line, does it mean that `media[idx].ssrcs` wouldn't be an array with a single element but directly an object?

**Comment by ibc** [comment]
OK it was a bug in my example/test SDP.

But, I don't understand yet why an SDP with a single `a=ssrc` line generates an array in `media[idx].ssrcs` while other rules generate a single value.

**Comment by ibc** [comment]
Yet another question:

```js
    { //a=rid:1 send max-width=1280;max-height=720;max-fps=30;depend=0
      push: 'rids',
      reg: /^rid:([\d\w]+) (\w+)(?: ([\S| ]*))/,
      names: ['id', 'direction', 'config'],
      format: function (o) {
        return (o.config) ? "rid:%s %s %s" : "rid:%s %s";
      }
    },
```

`id` is written as a string (`%s`) but, if `a=rid:1 send` then `id` becomes `1` (number rather than string), why? If it's `a=rid:a1 send` then `id` becomes a string "a1".

Does the lib automatically convert to number when possible?

**Comment by ibc** [comment]
It seems that `toIntIfInt()` does it...

**Comment by clux** [comment]
> But, I don't understand yet why an SDP with a single a=ssrc line generates an array in media[idx].ssrcs while other rules generate a single value.

Grammar that marks the attribute with `push` automatically assumes the values needs to be in an array.

> Does the lib automatically convert to number when possible?

Yeah, I think there may be a way to force it not to be if necessary. Let me refresh my memory.

**Comment by ibc** [comment]
> Grammar that marks the attribute with push automatically assumes the values needs to be in an array.

opps, I should have figured it out...
