### ISSUE TITLE
sdp transform parse webrtc  sdp error 

### ISSUE THREAD

**Issue by notedit** [clux/sdp-transform#64]
Error handling SDP offer:  TypeError: sdp.split is not a function
    at Object.exports.parse (/Users/xiang/Work/soupserver/node_modules/sdp-transform/lib/parser.js:46:7)

i did not dig yet,  just report here.

**Comment by murillo128** [comment]
Are you sure you are passing the SDP string and not the SDP offer object?

**Comment by notedit** [comment]
yes,  it is sdp string.

maybe it is because of  i change the bandwidth of the sdp.  

if i do not change the bandwidth, i will parse well.

**Comment by notedit** [comment]
sorry my fault
