### ISSUE TITLE
libsdptransform: C++ version of sdp-transform

### ISSUE THREAD

**Issue by ibc** [clux/sdp-transform#67]
https://github.com/ibc/libsdptransform/

:)

**Comment by clux** [comment]
Hah, awesome. I originally had a C++ library and wanted a JavaScript library and wrote this. We have come full circle.

Looks pretty clean, apart from the hard tabs (you monster).
I'm surprised the [hacky string coercion that's in this library](https://github.com/clux/sdp-transform/blob/master/lib/parser.js#L1-L3) translated into C++ at all.

**Comment by ibc** [comment]
> Looks pretty clean, apart from the hard tabs (you monster).

Nobody is perfect (even those who use tabs) :)

> I'm surprised the hacky string coercion that's in this library translated into C++ at all.

Yep, I think we must change that (even in the JavaScript lib). Having to check and "cast" the type of a value (in so many fields) make the API hard and dangerous. I'm considering the following:

`names` in each grammar may be an array of `{ name:NAME, type:TYPE }`. Values of `TYPE` can be `s` (string), `d`(number) or `f` (float). So, when parsing, rather than using `toIntIfInt()` we could just check the associated `TYPE` and make the corresponding type conversion. This way, the type of a value would be guaranteed.

What do you think?

**Comment by ibc** [comment]
Yeah, having a separate `types` array should also work and make it easier.

**Comment by ibc** [comment]
> But you'd have to go through every single matched value with the RFCs, which is a bit of a pain.

Humm, IMHO it would be just about using the same type as the corresponding formatter (%s, %d).

**Comment by clux** [comment]
Yeah, sometimes the type information overlaps a bit in there. Although [sometimes it's more complicated](https://github.com/clux/sdp-transform/blob/master/lib/grammar.js#L104)

**Comment by clux** [comment]
Optional regex matches would also be annoying to deal with here :/

**Comment by ibc** [comment]
Not sure if I see the problem. `format` is just for the writer. My concern about fixed types is just for the parser. Do I miss something?

**Comment by ibc** [comment]
Well, this is problematic:

```c++
std::regex("^rtcp-fb:(\\*|\\d*) trr-int (\\d*)")
```

so in those cases, it should be "string" (IMHO).

**Comment by ibc** [comment]
Oppss, I think I did it: https://github.com/ibc/libsdptransform/compare/typed

:)

What do you think? I could do the same in `sdp-transform`.

**Comment by ibc** [comment]
I've also documented all the grammar: https://github.com/ibc/libsdptransform/blob/master/doc/Grammar.md

**Comment by clux** [comment]
Had a quick look now. It seems sensible. Looks like most of the logic is in handling the magic `'s'`, `'d'` and `'f'` char literals everywhere.

Think the same approach would work well here, although we may break a few cases where strings that are really defined as strings in the spec, are often used as integers (like the common `a=mid:1` from the ANAT spec). If people are expecting things like that being integers (which they are 99% of the time), then they're in for a surprise.

It's a worthwhile change in my book though. If you want to have a go herein, go for it :-)

**Comment by ibc** [comment]
> we may break a few cases where strings that are really defined as strings in the spec, are often used as integers (like the common `a=mid:1` from the ANAT spec).

In fact, and at least in WebRTC, such an attribute is a string:

* Chrome: `a=mid:audio`
* Firefox: `a=mid:sdparta_0`

BTW I have a "problem". Some fields are mandatory as per spec, no matter they are empty strings. For example:

```js
  v: [{
    name: 'version',
    reg: /^(\d*)$/
  }],

  o: [{ //o=- 20518 0 IN IP4 203.0.113.1
    // NB: sessionId will be a String in most cases because it is huge
    name: 'origin',
    reg: /^(\S*) (\d*) (\d*) (\S*) IP(\d) (\S*)/,
    names: ['username', 'sessionId', 'sessionVersion', 'netType', 'ipVer', 'address'],
    format: '%s %s %d %s IP%d %s'
  }],
```

It seems that `v=` is valid (it shouldn't IMHO). Also, it seems that the `address` field in `o=` is optional (`\S*`), or in other words, it can be an empty string.

The thing is that, in both `sdp-transform` and `libsdptransform`, we ignore fields with empty string as value (we do not insert those fields into the corresponding object. So, it could generate problems:

```js
var address = session.origin.address;

console.log(address.length);
// PUMP!
```

```c++
std::string address = session.at("origin").at("address");
// PUMP!
```

Should we make the grammar syntax more strict by disallowing empty strings (for mandatory string fields)?

**Comment by ibc** [comment]
Or perhaps we should fill keys with empty string as value?

**Comment by clux** [comment]
> In fact, and at least in WebRTC, such an attribute is a string

huh, TIL.

> Or perhaps we should fill keys with empty string as value?

Yeah, I think parsing them as optional values is probably the way to go. We already have regexes with optional fields (though they are usually at the end), and format functions that uses '%v' (void value) conditionally. We should probably be able to deal with optionals for the types array as well. As long as it zips with the names array, it shouldn't be any harder to work out.

**Comment by clux** [comment]
The [extmap](https://github.com/clux/sdp-transform/blob/master/lib/grammar.js#L98-L105) grammar is a probably a good place to start as it does all the weird things.

**Comment by ibc** [comment]
We have the fields (`names`) and now also the types (in the C++ version). So yes, when doing the parsing we could ensure that all the string fields that have no value (optional ones) get an empty string as value. But, that wouldn't work with integers.

So, having `a=candidate:0 1 UDP 2113667327 203.0.113.1 54400 typ host` it could generate this:

```js
{
	foundation  : "0",
	component   : 1,
	transport   : "UDP",
	priority    : 2113667327,
	ip          : "203.0.113.1",
	port        : 54400,
	type        : "host",
	raddr       : "",
	tcptype     : ""
}
```

Note that `rport`, `generation` `network-id` and `network-cost` would not be included in the object because they are integers.

Not sure if I like this. The real problem I mean is that there are per spec mandatory fields (such as the `v=(\S*)` that MUST really be an string, even empty. However, in some other cases there are optional fields.

What I would like is that mandatory fields (even if they are empty strings) have always a value (even an empty string). But optional fields should not be included unless they have a non empty string as value.

And this is complex because we don't have a grammar field telling which names are mandatory fields. But we could add it:

In the C++ `candidates` grammar:

```c++
// names:
{ "foundation", "component", "transport", "priority", "ip", "port", "type", "raddr", "rport", "tcptype", "generation", "network-id", "network-cost" },
// types:
{ 's', 'd', 's', 'd', 's', 'd', 's', 's', 'd', 's', 'd', 'd', 'd', 'd' },
// mandatory:
{ 0, 1, 2, 3, 4, 5, 6 }
```

Then, in `parser.cpp`:

```c++
void attachProperties(
	const std::smatch& match,
	json& location,
	const std::vector<std::string>& names,
	const std::string& rawName,
	const std::vector<char>& types
	const std::vector<int>& mandatory
)
{
	if (!rawName.empty() && names.empty())
	{
		location[rawName] = toType(match[1].str(), types[0]);
	}
	else
	{
		for (size_t i = 0; i < names.size(); ++i)
		{
			if (
				i + 1 < match.size() &&
				(
					!match[i + 1].str().empty() ||
					(types[i + 1] == 's' && mandatory.find(i) != mandatory.end())
				)
			)
			{
				location[names[i]] = toType(match[i + 1].str(), types[i]);
			}
		}
	}
}
```

This way, mandatory strings that can be empty would always have a string value in the object.

**Comment by ibc** [comment]
Or simpler, just document it: https://github.com/ibc/libsdptransform/blob/master/doc/Grammar.md#grammar

**Comment by ibc** [comment]
Nothing to fix here :)
