### ISSUE TITLE
Name only parameters are ignored by parseParams

### ISSUE THREAD

**Issue by manuc66** [clux/sdp-transform#70]
Hi 

I noticed that in ST2110-20 the `interlace` parameter is a standalone declaration and do not have a value.
(See in this validation library: https://github.com/Streampunk/sdpoker/blob/b56fc0e0f5c0fd00a0696aac45795db2a660ea43/checkST2110.js#L607 )

In this case the parameter is omitted from the result structure.
From my investigation this  due to this this condition : https://github.com/clux/sdp-transform/blob/17386b7ea7a8ac917156c4af5a500503905a989b/lib/parser.js#L68

**Comment by clux** [comment]
Released the fix in sdp-transform@2.4.1

Thanks again :smile:
