### ISSUE TITLE
rtcp-fb invalid order after deserialization.

### ISSUE THREAD

**Issue by sergeyfsv-da** [clux/sdp-transform#72]
The parser does not keep the order of elements in SDP. So, if the source SDP looks like this:
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

After the deserialization, processing and serialization back it will look like this:

a=rtpmap:100 H264/90000
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli

FF/Chrome does not accept such offer/answers when rtcp-fb does not follow right after a=rtpmap

**Comment by clux** [comment]
Ugh. Another context within an a-line. Thanks for the report. :+1: 

This is unfortunately a non-trivial thing to fix at the moment because the only context we keep track of is which a-line something belongs to. This would need to book-keep rtpmaps as a context within an a-line.

It might even have to be a breaking change because `rtp` is already a struct on each media line.

It'd be worth fixing, but I don't have much time to look at this these days unfortunately. I can review and merge sensible PRs with tests.

**Comment by ibc** [comment]
> FF/Chrome does not accept such offer/answers when rtcp-fb does not follow right after a=rtpmap

This is a bug in Chrome then. Have you reported it?

**Comment by ibc** [comment]
BTW I don't think Chrome fails to parse the above SDP. I create `sdp-transform` Objects with the corresponding remote SDP/RTP parameters and then serialize it into a remote SDP (and call `peerconnection.setRemoteDescription()` with it). This is how the `m =video` section looks:

```
m=video 7 RTP/SAVPF 101 102 103 104
c=IN IP4 127.0.0.1
a=rtpmap:101 VP8/90000
a=rtpmap:102 rtx/90000
a=rtpmap:103 H264/90000
a=rtpmap:104 rtx/90000
a=fmtp:102 apt=101
a=fmtp:103 packetization-mode=1;profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:104 apt=103
a=rtcp-fb:101 goog-remb 
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack 
a=rtcp-fb:101 nack pli
a=rtcp-fb:103 goog-remb 
a=rtcp-fb:103 ccm fir
a=rtcp-fb:103 nack 
a=rtcp-fb:103 nack pli
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=setup:actpass
a=mid:video
a=sendonly
a=ice-ufrag:0zd0zpioqonstalh
a=ice-pwd:l0eh86npr1k1mb6q2dn2trwuce1ankn3
a=candidate:udpcandidate 1 udp 1078862079 1.2.3.4 45120 typ host
a=end-of-candidates
a=ice-options:renomination
a=ssrc:20679135 msid:recv-stream-54866563 consumer-video-54866563
a=ssrc:20679135 mslabel:recv-stream-54866563
a=ssrc:20679135 label:consumer-video-54866563
a=ssrc:20679135 cname:N6s8U+to3Lj2ae9j
a=ssrc:90687115 msid:recv-stream-54866563 consumer-video-54866563
a=ssrc:90687115 mslabel:recv-stream-54866563
a=ssrc:90687115 label:consumer-video-54866563
a=ssrc:90687115 cname:N6s8U+to3Lj2ae9j
a=ssrc-group:FID 20679135 90687115
a=rtcp-mux
a=rtcp-rsize
```

And it just works in Chrome.

**Comment by ibc** [comment]
We should close this issue as there is no issue at all.

**Comment by ibc** [comment]
Can we close this issue? I'm pretty sure there is no issue at all and what sdp-transform does it perfectly valid.
