### ISSUE TITLE
Number of audio channels

### ISSUE THREAD

**Issue by njh** [clux/sdp-transform#83]
Hi!

Thanks for writing `sap-transform` 🙂 

I am trying to use it for parsing Audio over IP (AES67) SDP descriptions - which may include multiple channels of audio as Linear PCM (`L16` / `L24`).

Here is a cut-down example SDP file:
```
v=0
o=- 1423986 1423994 IN IP4 169.254.98.63
s=AOIP44-serial-1614 : 2
c=IN IP4 239.65.125.63/32
t=0 0
m=audio 5004 RTP/AVP 97
a=recvonly
a=rtpmap:97 L24/48000/2
```

On parsing the SDP, the result is:
```json
{
  "version": 0,
  "origin": {
    "username": "-",
    "sessionId": 1423986,
    "sessionVersion": 1423994,
    "netType": "IN",
    "ipVer": 4,
    "address": "169.254.98.63"
  },
  "name": "AOIP44-serial-1614 : 2",
  "connection": {
    "version": 4,
    "ip": "239.65.125.63/32"
  },
  "timing": {
    "start": 0,
    "stop": 0
  },
  "media": [{
    "rtp": [{
      "payload": 97,
      "codec": "L24",
      "rate": 48000,
      "encoding": 2
    }],
    "fmtp": [],
    "type": "audio",
    "port": 5004,
    "protocol": "RTP/AVP",
    "payloads": 97,
    "direction": "recvonly"
  }]
}
```

Initially I was a bit puzzled by how to get the number of audio channels and then I realised that it ended up in `encoding`.

RFC4566 says:
```
a=rtpmap:<payload type> <encoding name>/<clock rate> [/<encoding parameters>]
...
For audio streams, <encoding parameters> indicates the number
of audio channels.  This parameter is OPTIONAL and may be
omitted if the number of channels is one, provided that no
additional parameters are needed.
```

Do you think it would make sense to set a `channels` property if the media type is `audio`?
I guess the disadvantage is that it would require some code and may be a breaking API change?

nick.

**Comment by ibc** [comment]
sdp-transform is a "context-less" SDP parsing library. Other than identifying `a=` lines after a `m=` lines, it does not keep state regarding this is an "audio" section or a "video" section or whatever, so the `a=rtpmap` parse does not know whether this is an audio codec or not and cannot apply conditional variables naming.

In short: no, just use the `encoding` field which, as per spec, means "the number of audio channels" :)

**Comment by njh** [comment]
Ok, thanks for considering this.

It is probably easier to do this in my own code then 👍
