### ISSUE TITLE
TTL for multicast addresses

### ISSUE THREAD

**Issue by njh** [clux/sdp-transform#84]
Hi!

Thanks for writing `sap-transform` 🙂 

I am trying to use it for parsing Audio over IP (AES67) SDP descriptions - which typically uses IP multicast.

Here is an example Connection Data line:
```
c=IN IP4 239.65.125.63/32
```

Which results in:
```json
  "connection": {
    "version": 4,
    "ip": "239.65.125.63/32"
  },
```

RFC4566 says for a multicast address the format is:
```
<base multicast address>[/<ttl>]/<number of addresses>
...
```

So to get just the IP address, I have been doing:
```javascript
ipAddress = sdp.connection.ip.split('/')[0]
```

Do you think it might be worth parsing out the TTL and number of addresses within the `sap-transform` library? This might be a breaking change for people already using addresses with TTL values - as seen in the SMPTE ST2022 and ST2110 example files.

nick.

**Comment by clux** [comment]
Hm.. Not entirely sure it's worth it.

As you say, it is __technically__ a breaking change, and by semver definition it should require a major bump.. unless you can argue that it's a "bug in the parsing" that just super rarely happens to break people's code. 

Interestingly, your code would actually not be broken by such a change, but code parsing for the second part of the split would. But the people who are parsing for that might appreciate the convenience anyway.

At any rate, if this were to be done, it should probably be done in a backwards compatible way, but not quite sure how to do that sanely atm.

**Comment by njh** [comment]
Ok, if you aren't keep, then it doesn't sound like worth the effort.

I will close.
