### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by sheikx1221** [clux/sdp-transform#92]
[This package](https://www.jsdelivr.com/package/npm/sdp-transform) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by clux** [comment]
It has "main" set to `./lib/` which ought to resolve fully to `./lib/index.js` - at least with with node's resolver - is that not enough?

**Comment by ibc** [comment]
The requester doesn't know that sdp-transform does not include a single bundled JS file, which is what such a CDN expects. I'd just close this issue.
