### ISSUE TITLE
Argument of parseSimulcastStreamList()

### ISSUE THREAD

**Issue by hintertupferbene** [clux/sdp-transform#95]
Hi, the README tells that `parseSimulcastStreamList()` gets the `attrs1` or `attrs2` string of the `a=simulcast` line and shows the example
```
sdpTransform.parseSimulcastStreamList(res.media[1].simulcast.attrs1);
```
Do I get this right, that `attrs1` and `attrs2` should be replaced by `list1` and `list2` in the README (according to the [grammar](https://github.com/clux/sdp-transform/blob/d8b446d81c62aa23e9ceee6a2fe7dd01f9ec8198/lib/grammar.js#L357))? If yes, do you want me to provide a PR?

**Comment by clux** [comment]
It does look like `parseImageAttributes` and `parseSimulcastStreamList` produces different names for their attrs, unlike what the readme says. Yeah, sure, a README pr is an easy merge here. Thank you!
