### ISSUE TITLE
sdp not working in H264 high profile

### ISSUE THREAD

**Issue by stevejia** [clux/sdp-transform#98]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/26504342/203679470-3acf8ec2-3d16-4be4-a4bd-a463c36e2f1a.png">
when use base line(42e01f), it works fine.
but when change profile-level-id to '64001f'(high profile), it does‘t work anymore。
I change sdp format like offer format at my local， it works fine.
could you please help to update sdp format just like the origin offer format?😊

**Comment by clux** [comment]
you could try to match the grammar for a=fmtp lines (which i assume you are referring to with profile-level-id).
code for it is here: https://github.com/clux/sdp-transform/blob/024554260bd7a732ae5b2e04dad0fc18cd624ab9/lib/grammar.js#L66-L73

**Comment by stevejia** [comment]
additional, can i adjust the order by configuring options?

**Comment by clux** [comment]
this library is not particularly smart about order.
we just write out the order we see get the various a-lines in
https://github.com/clux/sdp-transform/blob/master/lib/writer.js#L52-L59

i don't think it's something anything on a receiving end should care about?

**Comment by stevejia** [comment]
> this library is not particularly smart about order. we just write out the order we see get the various a-lines in https://github.com/clux/sdp-transform/blob/master/lib/writer.js#L52-L59
> 
> i don't think this is something any receiving side should care about tho?

gotcha～ thanks alot！
